# Site settings
title: "Blog of Clark.King"
email: "wskongdesheng@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  Awesome playground for Clark King.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wskongdesheng.github.io" # the base hostname & protocol for your site
twitter_username: megabee2
github_username:  wskongdesheng

# Build settings
markdown: kramdown
excerpt_separator: ""
